export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';

export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';

export const EDIT_TASK_STATUS_SUCCESS = 'EDIT_TASK_STATUS_SUCCESS';
export const EDIT_TASK_TEXT_SUCCESS = 'EDIT_TASK_TEXT_SUCCESS'